workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE != $DOCS_AUTOCOMMIT_TITLE
    - if: $CI_COMMIT_BRANCH =~ /^manticore-.*$/ && $CI_COMMIT_TITLE != $DOCS_AUTOCOMMIT_TITLE
    - if: $TEST || $WHAT

# to skip ci add [ci skip] or [skip ci] in commit message in any capitalization

stages:
  - build
  - publish
  
.redhat_based:
  stage: build
  interruptible: true
  tags:
    - docker
  script:
    - cmake -DPACK=1 .
    - make -j2 package
  artifacts:
    paths:
      - manticore*.rpm
    when: on_success
    expire_in: 12 hrs

.debian_based:
  stage: build
  interruptible: true
  tags:
    - docker
  script:
    - cmake -DPACK=1 .
    - make -j2 package
  artifacts:
    paths:
      - manticore*deb
    when: on_success
    expire_in: 12 hrs

rhel7:
  extends:
    - .redhat_based
  image: registry.gitlab.com/manticoresearch/dev/centos7_python:394

rhel8:
  extends:
    - .redhat_based
  image: registry.gitlab.com/manticoresearch/dev/centos8_python:394

stretch:
  extends:
    - .debian_based
  image: registry.gitlab.com/manticoresearch/dev/stretch_python:394

xenial:
  extends:
    - .debian_based
  image: registry.gitlab.com/manticoresearch/dev/xenial_python:394

bionic:
  extends:
    - .debian_based
  image: registry.gitlab.com/manticoresearch/dev/bionic_python:394

focal:
  extends:
    - .debian_based
  image: registry.gitlab.com/manticoresearch/dev/focal_python:394

buster:
  extends:
    - .debian_based
  image: registry.gitlab.com/manticoresearch/dev/buster_python:394

publish:
  stage: publish
  interruptible: true
  tags:
    - dev-host
  script:
    - echo "Collected packages"
    - ls -1
    - ~/upload_repo.sh
  dependencies: [rhel7, rhel8, stretch, xenial, bionic, buster, focal]
